$axure.loadCurrentPage({
  "url":"page_2.html",
  "generationDate":new Date(1394117303908.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1b7496c557db48a4a3aad282a8dbfd26",
    "type":"Axure:Page",
    "name":"Page 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3edf69a2173d4a5c9266847bdb25e943",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":234},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"£"},
{
          "id":"8a1e6cb2bedb4807a6d32ebeb801bd19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":239},
            "size":{
              "width":134,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"287fbd0874e94225a42bd2e8320ed5b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":239},
                "size":{
                  "width":134,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee42059b3acb4efea86187a289025454",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":264},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"£"},
{
          "id":"70599a5f94f741b09ed0f62df6f7bd3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":269},
            "size":{
              "width":134,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"349162d368fe4117b80d92c552d714a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":269},
                "size":{
                  "width":134,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80e15cb3e0eb41aeaaec718361fd4888",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":299},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"£"},
{
          "id":"87642cdcdd67467e8c8eff9589deaaf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":304},
            "size":{
              "width":134,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b958a4e5f3a46d0a3ffd1f7f47f8c5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":304},
                "size":{
                  "width":134,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe696e2e27e74ef8ae1944786aa764de",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":329},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"£"},
{
          "id":"68f9f3551eef4252a8c0a26ece86fe87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":334},
            "size":{
              "width":134,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"705e2382541c40318ac181b8f0404d1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":334},
                "size":{
                  "width":134,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fae52239a03449d9a7dcdbb4186e12e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":401},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"£"},
{
          "id":"651b4a99f87e45999ebdbaabc3ca0bdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":406},
            "size":{
              "width":134,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9901e168ca44746ade347360f0b04dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":406},
                "size":{
                  "width":134,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db40474ecc564ac8a02e6c6a4f98053b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":431},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"£"},
{
          "id":"2e63545d49e6449190d1b83869465330",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":436},
            "size":{
              "width":134,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"428fd74766494fd28315030b7769d1d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":436},
                "size":{
                  "width":134,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37670ed6ad7f4a26823dec7c9d90ebd3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":461},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"£"},
{
          "id":"0c0bd2c5fd774e0193279690b90d5cf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":466},
            "size":{
              "width":134,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3253ce5a980499493ad597515168e1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":466},
                "size":{
                  "width":134,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb97d875b4c84ae6b7363337a2fca9df",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":491},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"£"},
{
          "id":"1617cde66a474334a7933c727b4073fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":496},
            "size":{
              "width":134,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d04649a0d964486b727552b6ddd81a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":496},
                "size":{
                  "width":134,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6779d07317445fc8a065ab551110f7e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":521},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"£"},
{
          "id":"725ae2f2b968470aa561363278753297",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":526},
            "size":{
              "width":134,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b346d7f6e659473f89150d9b17e2c931",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":526},
                "size":{
                  "width":134,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7a312f003e147949b6918378f06827b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":551},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"£"},
{
          "id":"ba9563486b9341568853efac73fece35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":556},
            "size":{
              "width":134,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"902d8f1cd5c1481fbe1c2ca2215a8890",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":556},
                "size":{
                  "width":134,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c07fa9810b240b78f1791242b874edd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":581},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"£"},
{
          "id":"8c8036eb6034459c9497049f0fe44a98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":586},
            "size":{
              "width":134,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35e31c020db1443586af76960b4c6b94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":586},
                "size":{
                  "width":134,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ac1374a4e5a489eae5cd9e13828f44a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":46,
              "y":375},
            "size":{
              "width":121,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cf2e6660fe64668b3564d306bbfd3f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":46,
                  "y":375},
                "size":{
                  "width":121,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c97569a2e1034a58aec3ebee64c31d3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":46,
              "y":209},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb70a268c9d44013817868f60692b1f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":46,
                  "y":209},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac5b3b2998614e7f8d44404e25c42796",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":845},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 4 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"page_4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9d64314a9b6c471a8ae71f81b9ba05c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":46,
              "y":82},
            "size":{
              "width":371,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfb0872099bc4b248d8517842524eccd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":46,
                  "y":82},
                "size":{
                  "width":371,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d52f37d7dc514c6692dfc532821faab8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d948765b287e4910a87b544c288d4203"},
{
          "id":"209a296cefcb462baaa40dac4ed15a25",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"496274b40d464212b92db3b4da6e7759"},
{
          "id":"aeaf7a63335347219bc5b94b965dd371",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":669},
            "size":{
              "width":70,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"e95de14c4ab5419890fe197ce99cb81a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":670},
            "size":{
              "width":128,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"File"},
{
          "id":"a6dfd1b849e04e26b3e08202c204e99e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":670},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"Name of document"},
{
          "id":"2e63fabd1e004c4997084ede1893c020",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":785},
            "size":{
              "width":152,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6f069ef9202a4e0aa1d60e5cc8d34b6c",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":705},
            "size":{
              "width":200,
              "height":70}},
          "adaptiveStyles":{
}},
{
          "id":"8e44804050994359874333e12ddc8bad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":50,
              "y":638},
            "size":{
              "width":214,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4ee1521a02a424dac61fb1cb990c776",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":50,
                  "y":638},
                "size":{
                  "width":214,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37be88c86f7c46d797550842ca64080d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":381.5,
              "y":845},
            "size":{
              "width":114,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 4 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"page_4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9282d969bf7140b2aec41a1cde6a3804",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":66,
              "y":125},
            "size":{
              "width":181,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c607cd96e1f94369a4ad19e568f50c07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":66,
                  "y":125},
                "size":{
                  "width":181,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"024aec400b4e4e2fbd237e0af7835a7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":66,
              "y":150},
            "size":{
              "width":204,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c08d08468f934299880bf4bcf8afe72f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":66,
                  "y":150},
                "size":{
                  "width":204,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62db019c2e2b47c5929e88cc9238a2a2",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":45,
              "y":149},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be5dc47f5b77439c8ae4db6e3c1f5c9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":45,
                  "y":149},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"04a57627858949d5a61667dd0c15c1ea",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":45,
              "y":123},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"318d1bf8c1744291adfc7eb5c614dd8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":45,
                  "y":123},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"705b83f6beed4975b4199623ae2fb5a7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":190},
            "size":{
              "width":693,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/page_2/u66_line.png"}},
{
          "id":"f1d4677b901a4388bf51a06c581eb1b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC0000,
              "opacity":1},
            "location":{
              "x":257,
              "y":123},
            "size":{
              "width":363,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7abc339ab8134fbfa71b157e0c02120c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Italic', 'Arial'",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000,
                  "opacity":1},
                "location":{
                  "x":257,
                  "y":123},
                "size":{
                  "width":363,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9deac8d84064f77b9c91924ea58093b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":845},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"page_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "d948765b287e4910a87b544c288d4203":{
      "packageId":"d948765b287e4910a87b544c288d4203",
      "type":"Axure:Master",
      "name":"Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2924b952875d4489ab74cb86a062a59e",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "location":{
                "x":50,
                "y":10},
              "size":{
                "width":914,
                "height":167}},
            "adaptiveStyles":{
},
            "masterId":"87466a8fbaf547b49be50dd00f16e7b7"}]}},
    "87466a8fbaf547b49be50dd00f16e7b7":{
      "packageId":"87466a8fbaf547b49be50dd00f16e7b7",
      "type":"Axure:Master",
      "name":"FAF master item1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2cb16a91df174a58b1853813a7c2a25e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":138,
                "y":32},
              "size":{
                "width":372,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5e3cbfbfa8846858de22a890300033b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":138,
                    "y":32},
                  "size":{
                    "width":372,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e06253119b6d40388b80ff6c7580352b",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":26,
                "y":60},
              "size":{
                "width":914,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u4_line.png"}},
{
            "id":"7e42bfd1f3dc455f940d349359905969",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":26,
                "y":11},
              "size":{
                "width":86,
                "height":49}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bf912c586fdf4023b943abcd9d909a0a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":26,
                    "y":11},
                  "size":{
                    "width":86,
                    "height":49}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.jpg"}}]}},
    "496274b40d464212b92db3b4da6e7759":{
      "packageId":"496274b40d464212b92db3b4da6e7759",
      "type":"Axure:Master",
      "name":"Chat box",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b8b1c03f153c4b119935845a2defc146",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":764,
                "y":90},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2d748f12d03747f3ad0ff88243c80ad8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":764,
                    "y":90},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/page_1/u22.png"}}]}}},
  "objectPaths":{
    "3edf69a2173d4a5c9266847bdb25e943":{
      "scriptId":"u0"},
    "8a1e6cb2bedb4807a6d32ebeb801bd19":{
      "scriptId":"u1"},
    "287fbd0874e94225a42bd2e8320ed5b0":{
      "scriptId":"u2"},
    "ee42059b3acb4efea86187a289025454":{
      "scriptId":"u3"},
    "70599a5f94f741b09ed0f62df6f7bd3f":{
      "scriptId":"u4"},
    "349162d368fe4117b80d92c552d714a8":{
      "scriptId":"u5"},
    "80e15cb3e0eb41aeaaec718361fd4888":{
      "scriptId":"u6"},
    "87642cdcdd67467e8c8eff9589deaaf3":{
      "scriptId":"u7"},
    "3b958a4e5f3a46d0a3ffd1f7f47f8c5b":{
      "scriptId":"u8"},
    "fe696e2e27e74ef8ae1944786aa764de":{
      "scriptId":"u9"},
    "68f9f3551eef4252a8c0a26ece86fe87":{
      "scriptId":"u10"},
    "705e2382541c40318ac181b8f0404d1f":{
      "scriptId":"u11"},
    "3fae52239a03449d9a7dcdbb4186e12e":{
      "scriptId":"u12"},
    "651b4a99f87e45999ebdbaabc3ca0bdf":{
      "scriptId":"u13"},
    "f9901e168ca44746ade347360f0b04dc":{
      "scriptId":"u14"},
    "db40474ecc564ac8a02e6c6a4f98053b":{
      "scriptId":"u15"},
    "2e63545d49e6449190d1b83869465330":{
      "scriptId":"u16"},
    "428fd74766494fd28315030b7769d1d8":{
      "scriptId":"u17"},
    "37670ed6ad7f4a26823dec7c9d90ebd3":{
      "scriptId":"u18"},
    "0c0bd2c5fd774e0193279690b90d5cf0":{
      "scriptId":"u19"},
    "a3253ce5a980499493ad597515168e1d":{
      "scriptId":"u20"},
    "eb97d875b4c84ae6b7363337a2fca9df":{
      "scriptId":"u21"},
    "1617cde66a474334a7933c727b4073fc":{
      "scriptId":"u22"},
    "6d04649a0d964486b727552b6ddd81a6":{
      "scriptId":"u23"},
    "a6779d07317445fc8a065ab551110f7e":{
      "scriptId":"u24"},
    "725ae2f2b968470aa561363278753297":{
      "scriptId":"u25"},
    "b346d7f6e659473f89150d9b17e2c931":{
      "scriptId":"u26"},
    "a7a312f003e147949b6918378f06827b":{
      "scriptId":"u27"},
    "ba9563486b9341568853efac73fece35":{
      "scriptId":"u28"},
    "902d8f1cd5c1481fbe1c2ca2215a8890":{
      "scriptId":"u29"},
    "7c07fa9810b240b78f1791242b874edd":{
      "scriptId":"u30"},
    "8c8036eb6034459c9497049f0fe44a98":{
      "scriptId":"u31"},
    "35e31c020db1443586af76960b4c6b94":{
      "scriptId":"u32"},
    "7ac1374a4e5a489eae5cd9e13828f44a":{
      "scriptId":"u33"},
    "9cf2e6660fe64668b3564d306bbfd3f5":{
      "scriptId":"u34"},
    "c97569a2e1034a58aec3ebee64c31d3c":{
      "scriptId":"u35"},
    "fb70a268c9d44013817868f60692b1f7":{
      "scriptId":"u36"},
    "ac5b3b2998614e7f8d44404e25c42796":{
      "scriptId":"u37"},
    "9d64314a9b6c471a8ae71f81b9ba05c0":{
      "scriptId":"u38"},
    "dfb0872099bc4b248d8517842524eccd":{
      "scriptId":"u39"},
    "d52f37d7dc514c6692dfc532821faab8":{
      "scriptId":"u40",
      "2924b952875d4489ab74cb86a062a59e":{
        "scriptId":"u41",
        "2cb16a91df174a58b1853813a7c2a25e":{
          "scriptId":"u42"},
        "a5e3cbfbfa8846858de22a890300033b":{
          "scriptId":"u43"},
        "e06253119b6d40388b80ff6c7580352b":{
          "scriptId":"u44"},
        "7e42bfd1f3dc455f940d349359905969":{
          "scriptId":"u45"},
        "bf912c586fdf4023b943abcd9d909a0a":{
          "scriptId":"u46"}}},
    "209a296cefcb462baaa40dac4ed15a25":{
      "scriptId":"u47",
      "b8b1c03f153c4b119935845a2defc146":{
        "scriptId":"u48"},
      "2d748f12d03747f3ad0ff88243c80ad8":{
        "scriptId":"u49"}},
    "aeaf7a63335347219bc5b94b965dd371":{
      "scriptId":"u50"},
    "e95de14c4ab5419890fe197ce99cb81a":{
      "scriptId":"u51"},
    "a6dfd1b849e04e26b3e08202c204e99e":{
      "scriptId":"u52"},
    "2e63fabd1e004c4997084ede1893c020":{
      "scriptId":"u53"},
    "6f069ef9202a4e0aa1d60e5cc8d34b6c":{
      "scriptId":"u54"},
    "8e44804050994359874333e12ddc8bad":{
      "scriptId":"u55"},
    "e4ee1521a02a424dac61fb1cb990c776":{
      "scriptId":"u56"},
    "37be88c86f7c46d797550842ca64080d":{
      "scriptId":"u57"},
    "9282d969bf7140b2aec41a1cde6a3804":{
      "scriptId":"u58"},
    "c607cd96e1f94369a4ad19e568f50c07":{
      "scriptId":"u59"},
    "024aec400b4e4e2fbd237e0af7835a7d":{
      "scriptId":"u60"},
    "c08d08468f934299880bf4bcf8afe72f":{
      "scriptId":"u61"},
    "62db019c2e2b47c5929e88cc9238a2a2":{
      "scriptId":"u62"},
    "be5dc47f5b77439c8ae4db6e3c1f5c9b":{
      "scriptId":"u63"},
    "04a57627858949d5a61667dd0c15c1ea":{
      "scriptId":"u64"},
    "318d1bf8c1744291adfc7eb5c614dd8b":{
      "scriptId":"u65"},
    "705b83f6beed4975b4199623ae2fb5a7":{
      "scriptId":"u66"},
    "f1d4677b901a4388bf51a06c581eb1b1":{
      "scriptId":"u67"},
    "7abc339ab8134fbfa71b157e0c02120c":{
      "scriptId":"u68"},
    "c9deac8d84064f77b9c91924ea58093b":{
      "scriptId":"u69"}}});